### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by danielelkabes** [panates/putil-merge#6]
Hi team,

I've tried to contact you via email, but there is no response.
Can you please contact me back - daniel.elkabes@whitesourcesoftware.com

Thanks,

**Comment by danielelkabes** [comment]
@erayhanoglu

**Comment by danielelkabes** [comment]
@www-chique

**Comment by erayhanoglu** [comment]
Hello,
I did not understand why you are trying to contact us? Any way i didn't got an email from you.

**Comment by danielelkabes** [comment]
Hi @erayhanoglu 

Thank you for your response,

This is regarding a security issue, please check your spam or contact us at - daniel.elkabes@whitesourcesoftware.com or vulnerability@whitesourcesoftware.com

![image](https://user-images.githubusercontent.com/55395407/124554556-c470d680-de3e-11eb-8c64-55154e8c4a4b.png)

**Comment by erayhanoglu** [comment]
Sorry i couln't find the e mail. Can you please write your issue here?

**Comment by erayhanoglu** [comment]
By the way i ve just released a new version to update dependencies

**Comment by danielelkabes** [comment]
We usually prefer to share security issues in private, so they won't be abused by malicious actors before there been addressed with an appropriate fix.

Do you still prefer that we'll share it in this issue ?

**Comment by www-chique** [comment]
Hi @danielelkabes .
We appreciate your concern regarding pointing out a security issue and trying to contact us.
Neither have I received any email from you, nor was anything regarding "security issue" mentioned in the original message of this thread, and it lead to this misunderstanding.
We sincerely apologize for the situation.

I am not the author of this tool.
However, I did find out you creating a similar issue thread in some other repos as well, like [here](https://github.com/apexcharts/react-apexcharts/issues/252) and [here](https://github.com/ASaiAnudeep/deep-override/issues/2), in both of which you mentioned that you couldn't reach by email and asked the authors to email you. It's weird how none of the authors receive your email.
Can you please retry sending the email once again?
Otherwise, I'll let @erayhanoglu contact you via email as he is the author of this tool.
If I can be of any help, please let me know.

**Comment by danielelkabes** [comment]
Hi @www-chique, now and then the mails are transferred to spam, I sent the email only to e.hanoglu@panates.com, I've sent it twice, as of that please check your spam. I've sent another email now in the same thread.

If you are not the author of the tool @www-chique and not one of the maintainers, I can't send you the security issue at this point.

@erayhanoglu please let me know how do you want to proceed, as I mentioned we can share the full report here in the issue if that's what you prefer.

**Comment by erayhanoglu** [comment]
Hello daniel. I ve checked spam box but couldn't find your e mail. Can you sent it to erayhanoglu@gmail.com please.

**Comment by danielelkabes** [comment]
@erayhanoglu done.

**Comment by erayhanoglu** [comment]
I ve got your e mail. Thank you for your helpful vulnerability report. I ve fixed the issue.
